# iris模型训练

In [3]:
from sklearn import datasets

iris = datasets.load_iris();

In [4]:
# X 输入赋值，y 输出赋值
X = iris.data
y = iris.target

In [5]:
# 确认数据类型
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## 使用 scikit-learn 建模四步骤
1. 调用需要使用的模型类
2. 模型初始化
3. 训练
4. 预测

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
# 创建实例
knn = KNeighborsClassifier(n_neighbors = 1)

In [8]:
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=1)

In [9]:
knn.predict([[1,2,3,4]])

array([2])

In [10]:
# 多样本
x_test = [[1,2,3,4], [2,4,1,2]]
knn.predict(x_test)

array([2, 0])

In [11]:
knn_5 = KNeighborsClassifier(n_neighbors=5)

In [15]:
knn_5.fit(X, y)

KNeighborsClassifier()

In [16]:
knn.predict(x_test)

array([2, 0])